# Generated by Django 2.2 on 2020-12-07 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(blank=True, max_length=50)),
                ('line', models.CharField(blank=True, max_length=50)),
                ('line2', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=5, max_digits=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, upload_to='stores/')),
                ('hide', models.BooleanField(default=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='bookr.StoreLocation')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='bookr.Account')),
                ('products', models.ManyToManyField(blank=True, related_name='products', to='bookr.Item')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='bookr.Wallet')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='bookr.Product'),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookr.Store'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(blank=True, related_name='items', to='bookr.Item')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookr.Store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookr.Account')),
            ],
        ),
    ]
